In [0]:
import numpy as np
A=np.matrix([[0,0,0,1],[1,0,1,0],[0,1,0,1],[0,1,0,0]])

In [0]:
A=A.T

In [17]:
A

matrix([[0, 1, 0, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [1, 0, 1, 0]])

In [18]:
A.shape

(4, 4)

In [0]:
X=np.matrix([[i,-i] for i in range(A.shape[0])],dtype=float)

In [20]:
X    # number of nodex x node_feature_dim

matrix([[ 0.,  0.],
        [ 1., -1.],
        [ 2., -2.],
        [ 3., -3.]])

In [0]:
B=A*X

In [22]:
B

matrix([[ 1., -1.],
        [ 5., -5.],
        [ 1., -1.],
        [ 2., -2.]])

In [0]:
I=np.matrix(np.eye(A.shape[0]))

In [24]:
I   # Identity matrix to add self loops so that node embeddings can be added to itself

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [0]:
A_hat=A+I

In [26]:
A_hat*X

matrix([[ 1., -1.],
        [ 6., -6.],
        [ 3., -3.],
        [ 5., -5.]])

In [0]:
D=np.array(np.sum(A,axis=0))

In [37]:
D[0]

array([1, 2, 2, 1])

In [0]:
D=np.matrix(np.diag(D[0]))

In [39]:
D

matrix([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 1]])

In [40]:
A

matrix([[0, 1, 0, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [1, 0, 1, 0]])

In [41]:
D**2

matrix([[1, 0, 0, 0],
        [0, 4, 0, 0],
        [0, 0, 4, 0],
        [0, 0, 0, 1]])

In [43]:
D**-1

matrix([[1. , 0. , 0. , 0. ],
        [0. , 0.5, 0. , 0. ],
        [0. , 0. , 0.5, 0. ],
        [0. , 0. , 0. , 1. ]])

In [44]:
A

matrix([[0, 1, 0, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [1, 0, 1, 0]])

In [45]:
D**-1*A

matrix([[0. , 1. , 0. , 0. ],
        [0. , 0. , 0.5, 0.5],
        [0. , 0.5, 0. , 0. ],
        [1. , 0. , 1. , 0. ]])

In [0]:
#for normalization we do D**-1 and do matrix multiplication
# D**-1*A has weights across nodes =1 across row so when we add features
# from neighbouring nodes 

In [47]:
D**-1*A*X

matrix([[ 1. , -1. ],
        [ 2.5, -2.5],
        [ 0.5, -0.5],
        [ 2. , -2. ]])