In [0]:
import torch
!pip install --upgrade torch-scatter
!pip install --upgrade torch-sparse
!pip install --upgrade torch-cluster
!pip install --upgrade torch-spline-conv
!pip install torch-geometric

  Created wheel for torch-scatter: filename=torch_scatter-1.4.0-cp36-cp36m-linux_x86_64.whl size=2875297 sha256=870a5ada6bf7c61c7f252f6fb7488c19f18305c47d4818df7a99632d5e080fab
  Stored in directory: /root/.cache/pip/wheels/25/00/c4/1637b4b3003f29092f4fe2ad4b40dd10906269c1ac2dc82941
Successfully built torch-scatter
  Created wheel for torch-sparse: filename=torch_sparse-0.4.3-cp36-cp36m-linux_x86_64.whl size=3966456 sha256=7a914d9160f190d88a513dbdcc77ca42fad0f7118fa342260f718a450baa914b
  Stored in directory: /root/.cache/pip/wheels/02/66/2b/befece01c2516f9fb3e7b4d150bb2b871221c73657c9cd7735
Successfully built torch-sparse


In [0]:
edge_index=torch.tensor([[0,1,1,2],[1,0,2,1]],dtype=torch.long)# numedges x numedgefeatures

In [0]:

from torch_geometric.data import Data

In [0]:
x=torch.tensor([[-1],[0],[1]],dtype=torch.float)

In [0]:
data=Data(x=x,edge_index=edge_index)  #

In [0]:
#edge index stores which node in first row is connected to node in second row for same column
# can be helpful for storing bidirected as well as directed graphs
# as storing edges as adjacency matrix is really sparse and eat lot of memory


In [0]:
x # node feature matrix of shape num_nodes x num_node_features

tensor([[-1.],
        [ 0.],
        [ 1.]])

In [0]:
# -1,0,1 are features of nodes or it can also be embeddings representing the 
# features of nodes

In [0]:
data  

Data(edge_index=[2, 4], x=[3, 1])

In [0]:
# edge matrix first row shows source and second row shows the target node
# for same column

In [0]:
#Although the graph has only two edges, we need to define four index tuples to account for both directions of a edge.

In [0]:
from torch_geometric.datasets import TUDataset

In [0]:
dataset=TUDataset(root='tmp/ENZYMES',name='ENZYMES')

Extracting tmp/ENZYMES/ENZYMES.zip
Processing...
Done!


In [0]:
len(dataset)

600

In [0]:
dataset.num_classes

6

In [0]:
dataset.num_edge_labels

0

In [0]:
dataset.num_node_attributes

0

In [0]:
  dataset.num_node_labels

3

In [0]:
dataset.num_features

3

In [0]:
#600 graphs

In [0]:
data=dataset[0]

In [0]:
data

Data(edge_index=[2, 168], x=[37, 3], y=[1])

In [0]:
data.y

tensor([5])

In [0]:
data.edge_index

tensor([[ 0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
          3,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,
          7,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12,
         12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16,
         16, 16, 17, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 20, 20, 20,
         21, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25,
         25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28,
         28, 28, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 32,
         32, 32, 32, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 35, 35, 35,
         35, 35, 36, 36, 36, 36],
        [ 1,  2,  3,  0,  2,  3, 24, 27,  0,  1,  3, 27, 28,  0,  1,  2,  4,  5,
         28,  3,  5,  6, 29,  3,  4,  6,  7, 29,  4,  5,  7,  8,  5,  6,  8,  9,
         10,  6,  7,  9,  7,  8, 10, 11, 12,  7,  9, 11, 12,  9, 10, 12, 26

In [0]:
data.x  # node embeddings 

tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

In [0]:
data.y 
# numnodes, *    # shape when node level predictions
# 1,*   graph level predictions

tensor([5])

In [0]:
data.pos

In [0]:
data.is_directed()

False

In [0]:
data.is_undirected()

True

In [0]:
data.num_edges

168

In [0]:
# total edges if graph is undirected
(data.num_edges)/2

84.0